apiVersion: apps/v1
kind: Deployment
metadata:
  name: myslave
  namespace: development
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 1
  selector:
    matchLabels:
      app: myslave
  template:
    metadata:
      labels:
        app: myslave
    spec:
      automountServiceAccountToken: false
      containers:
      - name: myslave
        image: myslave:${DOCKER_IMAGE_TAG}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: "/actuator/health/liveness"
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: "/actuator/health/readiness"
            port: 8080
          periodSeconds: 10
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: "/actuator/health/liveness"
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10
          failureThreshold: 3
        resources:
          limits:
            cpu: 500m
            memory: 512M
          requests:
            cpu: 200m
            memory: 256M
